export const validationMsgs = {
  weakPassword: "Weak Password",
  passwordRequired: "Password is Required",
  currentPasswordRequired: "Current Password is Required",
  confirmPasswordRequired: "Confirm Password is Required",
  confirmPasswordNotMatch: "Confirm Password does not match",
  passwordMinLength: "Password should be atleast 8 characters",
  otpRequired: "OTP is Required",
  phoneNumberRequired: "Phone Number is Required",
  invalidPhoneNumber: "Invalid Phone Number",
  nameRequired: "Name is required",
  firstNameRequired: "First name is Required",
  lastNameRequired: "Last name is Required",
  emailRequired: "Email is Required",
  invalidEmail: "Invalid email address",
  dateRequired: "Date is required",
  dobRequired: "Date of birth is Required",
  bloodGroupRequired: "Blood Group is Required",
  countryRequired: "Country is Required",
  cityRequired: "City is Required",
  stateRequired: "State is Required",
  districtRequired: "District is Required",
  localBodyTypeRequired: "Local body type is Required",
  localBodyNameRequired: "Local body name is Required",
  wardNameRequired: "Ward name is Required",
  postOfficeRequired: "Post Office is Required",
  genderRequired: "Gender is Required",
  pinCodeRequired: "Pin code is Required",
  addressTypeRequired: "Address type is Required",
  qualificationTypeRequired: "Qualifications type is Required",
  certificateNumberRequired: "Certificate number is Required",
  certificateDateRequired: "Certificate date is Required",
  admissionNumberRequired: "Admission number is Required",
  institutionTypeRequired: "Institution type is Required",
  institutionRequired: "Institution is Required",
  communicationTypeRequired: "Communication type is Required",
  organizationNameRequired: "Organization name is Required",
  organizationTypeRequired: "Organization type is Required",
  organizationStartDateRequired: "Organization start date is Required",
  organizationEndDateRequired: "Organization end date is Required",
  registrationNumberRequired: "Registration number is Required",
  activityRequired: "Activity is Required",
  activityTypeRequired: "Activity type is Required",
  websiteRequired: "Website is Required",
  actionRequired: "Action is Required",
  reasonRequired: "Reason is Required",
  subjectRequired: "Subject is Required",
  orgRequired: "Organization is Required",
  addressRequired: "Address is Required",
  msgRequired: "Message is Required"
};
